image: "ubuntu:latest"


workflow:
  rules:
    - changes:
        - query.sql


stages:
  - runselect


runselect:

  image: alpine:latest

  stage: runselect

  tags:
    - skillfaktory
  before_script:
    - apt update
    - apt install mysql-client

  script:
    - mysql --user rfamro --host mysql-rfam-public.ebi.ac.uk --port 4497 --database Rfam -e 'source query.sql'
